Repository ThatRedKite/thatkitebot, pull requests merged in 2021-12, with the labels that each got.

#22 a few minor fixes
  thatkitebot/cogs/electronics.py
  thatkitebot/cogs/funstuffcog.py
Labels: enhancement

#29 Update laser.py
  thatkitebot/cogs/laser.py
Labels: bug, enhancement

#30 fix laser commands
  thatkitebot/cogs/laser.py
Labels: bug

#31 cache-related fixes and improvements
  thatkitebot/backend/cache.py
  thatkitebot/cogs/funstuffcog.py
Labels: bug, enhancement

#32 Image features
  .gitignore
  data/DejaVu Fonts License.txt
  data/DejaVuSans.ttf
  data/Open Sans Emoji Licence.txt
  data/OpenSansEmoji.ttf
  thatkitebot/cogs/imagecog.py
Labels: enhancement

#33 merge of version 3.4 to master
  .github/workflows/codeql-analysis.yml
  .gitignore
  data/DejaVu Fonts License.txt
  data/DejaVuSans.ttf
  data/Open Sans Emoji Licence.txt
  data/OpenSansEmoji.ttf
  thatkitebot/__main__.py
  thatkitebot/backend/url.py
  thatkitebot/cogs/funstuffcog.py
  thatkitebot/cogs/imagecog.py
Labels: bug, documentation, enhancement

#35 Added welcome command, caption color improvements and other
  thatkitebot/__main__.py
  thatkitebot/cogs/imagecog.py
  thatkitebot/cogs/listenercog.py
  thatkitebot/cogs/welcomecog.py
Labels: enhancement

#36 Last merge of the year
  requirements.txt
  thatkitebot/__main__.py
  thatkitebot/backend/cache.py
  thatkitebot/cogs/imagecog.py
  thatkitebot/cogs/listenercog.py
  thatkitebot/cogs/repost.py
  thatkitebot/cogs/settings.py
  thatkitebot/cogs/welcomecog.py
Labels: bug, documentation, enhancement

#38 fix welcome leaderboard
  thatkitebot/cogs/welcomecog.py
Labels: bug, high priority
